apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-system
  namespace: argocd
spec:
  project: default
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - Replace=true
      - Force=true
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.8.1 
    helm:
      releaseName: longhorn
      valuesObject:
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 3
        preUpgradeChecker:
          upgradeVersionCheck: true
        defaultSettings:
          defaultDataPath: /storage
        service:
          ui:
            type: LoadBalancer