kind: Namespace
apiVersion: v1
metadata:
  name: longhorn-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-system
  namespace: argocd
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.8.1 
    helm:
      releaseName: longhorn
      valuesObject:
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 3
        preUpgradeChecker:
          upgradeVersionCheck: true
      parameters:
        - name: defaultSettings.defaultDataPath
          value: /storage
        - name: service.ui.type
          value: LoadBalancer