apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: Replace=true
spec:
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 70.9.0
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        grafana:
          service:
            type: LoadBalancer
            loadBalancerIP: 192.168.1.132
          # additionalDataSources:
          #   - name: Prometheus
          #     type: prometheus
          #     access: proxy
          #     url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          #     isDefault: true
        prometheus:
          service:
            type: LoadBalancer
            loadBalancerIP: 192.168.1.131
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 20Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
