apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.140   # 🎯 assign your chosen static IP here
  selector:
    app: longhorn-ui
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
