apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.8.1 
    helm:
      releaseName: longhorn
      valuesObject:
        crd:
          force: true
        serviceAccount:
          create: true
          name: longhorn-service-account
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 3
        preUpgradeChecker:
          jobEnabled: false
          upgradeVersionCheck: false
        defaultSettings:
          defaultDataPath: /mnt/ssd
        service:
          ui:
            type: LoadBalancer