apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    chart: pihole
    targetRevision: 2.29.1
    helm:
      releaseName: pihole
      valuesObject:
        serviceWeb:
          loadBalancerIP: 192.168.1.150 
        serviceDns:
          loadBalancerIP: 192.168.1.151
        persistentVolumeClaim:
          enabled: true
          storageClass: longhorn
          size: 1Gi
        adminPassword: "default"
